create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";


  create table "public"."atualizar" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "numero" integer
      );


alter table "public"."atualizar" enable row level security;


  create table "public"."evaluations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "director_id" uuid not null,
    "member_name" text not null,
    "week_of" date not null,
    "rating_comunicacao" smallint,
    "rating_participacao" smallint,
    "rating_relacao_grupo" smallint,
    "rating_proatividade" smallint,
    "rating_entrega_metas" smallint,
    "is_destaque" boolean default false,
    "comments" text,
    "evaluation_type" text default 'member'::text,
    "rating_lideranca" smallint,
    "rating_flexibilidade" smallint,
    "text_delegacao" text
      );


alter table "public"."evaluations" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "notion_name" text,
    "user_role" text,
    "project_name" text,
    "assessoria" text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX atualizar_pkey ON public.atualizar USING btree (id);

CREATE UNIQUE INDEX evaluations_pkey ON public.evaluations USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."atualizar" add constraint "atualizar_pkey" PRIMARY KEY using index "atualizar_pkey";

alter table "public"."evaluations" add constraint "evaluations_pkey" PRIMARY KEY using index "evaluations_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."evaluations" add constraint "evaluations_director_id_fkey" FOREIGN KEY (director_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."evaluations" validate constraint "evaluations_director_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

create or replace view "public"."analytics_view" as  SELECT e.member_name,
    p.id AS profile_id,
    COALESCE(p.user_role, 'Não Cadastrado'::text) AS user_role,
    COALESCE(p.assessoria, 'Sem Assessoria'::text) AS assessoria,
    p.project_name,
    count(e.id) AS total_evaluations,
    COALESCE(round(avg(e.rating_comunicacao), 1), (0)::numeric) AS avg_comunicacao,
    COALESCE(round(avg(e.rating_participacao), 1), (0)::numeric) AS avg_participacao,
    COALESCE(round(avg(e.rating_relacao_grupo), 1), (0)::numeric) AS avg_relacao,
    COALESCE(round(avg(e.rating_proatividade), 1), (0)::numeric) AS avg_proatividade,
    COALESCE(round(avg(e.rating_entrega_metas), 1), (0)::numeric) AS avg_metas,
    COALESCE(round(avg(e.rating_lideranca), 1), (0)::numeric) AS avg_lideranca,
    COALESCE(round(avg(e.rating_flexibilidade), 1), (0)::numeric) AS avg_flexibilidade,
    COALESCE(round((((((((COALESCE(avg(e.rating_comunicacao), (0)::numeric) + COALESCE(avg(e.rating_participacao), (0)::numeric)) + COALESCE(avg(e.rating_relacao_grupo), (0)::numeric)) + COALESCE(avg(e.rating_proatividade), (0)::numeric)) + COALESCE(avg(e.rating_entrega_metas), (0)::numeric)) + COALESCE(avg(e.rating_lideranca), (0)::numeric)) + COALESCE(avg(e.rating_flexibilidade), (0)::numeric)) / (NULLIF(((((((
        CASE
            WHEN (avg(e.rating_comunicacao) IS NOT NULL) THEN 1
            ELSE 0
        END +
        CASE
            WHEN (avg(e.rating_participacao) IS NOT NULL) THEN 1
            ELSE 0
        END) +
        CASE
            WHEN (avg(e.rating_relacao_grupo) IS NOT NULL) THEN 1
            ELSE 0
        END) +
        CASE
            WHEN (avg(e.rating_proatividade) IS NOT NULL) THEN 1
            ELSE 0
        END) +
        CASE
            WHEN (avg(e.rating_entrega_metas) IS NOT NULL) THEN 1
            ELSE 0
        END) +
        CASE
            WHEN (avg(e.rating_lideranca) IS NOT NULL) THEN 1
            ELSE 0
        END) +
        CASE
            WHEN (avg(e.rating_flexibilidade) IS NOT NULL) THEN 1
            ELSE 0
        END), 0))::numeric), 1), (0)::numeric) AS overall_score
   FROM (public.evaluations e
     LEFT JOIN public.profiles p ON ((e.member_name = p.notion_name)))
  GROUP BY e.member_name, p.id, p.user_role, p.assessoria, p.project_name;


CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, email, notion_name, user_role, project_name, assessoria)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'notion_name',
    new.raw_user_meta_data ->> 'user_role',
    new.raw_user_meta_data ->> 'project_name',
    new.raw_user_meta_data ->> 'assessoria'
  );
  return new;
end;
$function$
;

grant delete on table "public"."atualizar" to "anon";

grant insert on table "public"."atualizar" to "anon";

grant references on table "public"."atualizar" to "anon";

grant select on table "public"."atualizar" to "anon";

grant trigger on table "public"."atualizar" to "anon";

grant truncate on table "public"."atualizar" to "anon";

grant update on table "public"."atualizar" to "anon";

grant delete on table "public"."atualizar" to "authenticated";

grant insert on table "public"."atualizar" to "authenticated";

grant references on table "public"."atualizar" to "authenticated";

grant select on table "public"."atualizar" to "authenticated";

grant trigger on table "public"."atualizar" to "authenticated";

grant truncate on table "public"."atualizar" to "authenticated";

grant update on table "public"."atualizar" to "authenticated";

grant delete on table "public"."atualizar" to "service_role";

grant insert on table "public"."atualizar" to "service_role";

grant references on table "public"."atualizar" to "service_role";

grant select on table "public"."atualizar" to "service_role";

grant trigger on table "public"."atualizar" to "service_role";

grant truncate on table "public"."atualizar" to "service_role";

grant update on table "public"."atualizar" to "service_role";

grant delete on table "public"."evaluations" to "anon";

grant insert on table "public"."evaluations" to "anon";

grant references on table "public"."evaluations" to "anon";

grant select on table "public"."evaluations" to "anon";

grant trigger on table "public"."evaluations" to "anon";

grant truncate on table "public"."evaluations" to "anon";

grant update on table "public"."evaluations" to "anon";

grant delete on table "public"."evaluations" to "authenticated";

grant insert on table "public"."evaluations" to "authenticated";

grant references on table "public"."evaluations" to "authenticated";

grant select on table "public"."evaluations" to "authenticated";

grant trigger on table "public"."evaluations" to "authenticated";

grant truncate on table "public"."evaluations" to "authenticated";

grant update on table "public"."evaluations" to "authenticated";

grant delete on table "public"."evaluations" to "service_role";

grant insert on table "public"."evaluations" to "service_role";

grant references on table "public"."evaluations" to "service_role";

grant select on table "public"."evaluations" to "service_role";

grant trigger on table "public"."evaluations" to "service_role";

grant truncate on table "public"."evaluations" to "service_role";

grant update on table "public"."evaluations" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Acesso total para Diretores e RH"
  on "public"."evaluations"
  as permissive
  for select
  to authenticated
using (((director_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND ((profiles.user_role = 'Diretor'::text) OR (profiles.assessoria = 'Recursos Humanos'::text)))))));



  create policy "Usuários podem criar avaliações"
  on "public"."evaluations"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = director_id));



  create policy "Usuários veem suas próprias avaliações"
  on "public"."evaluations"
  as permissive
  for select
  to authenticated
using ((auth.uid() = director_id));



  create policy "Leitura pública de perfis"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Usuários podem editar seu próprio perfil"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


