-- Registra reservas e resultados dos lembretes para impedir envios duplicados.
create table public.reminder_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  cycle_key date not null,
  cycle_type text not null check (cycle_type in ('weekly', 'biweekly')),
  channel text not null check (channel = 'email'),
  status text not null check (status in ('processing', 'sent', 'failed')),
  pending_kinds jsonb not null,
  resend_email_id text,
  attempted_at timestamptz not null default now(),
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  unique (user_id, cycle_type, cycle_key, channel)
);

alter table public.reminder_logs enable row level security;

-- Usuários comuns não acessam os logs; somente o worker server-side grava/lê.
revoke all on table public.reminder_logs from anon, authenticated;
revoke all on sequence public.reminder_logs_id_seq from anon, authenticated;
grant usage, select on sequence public.reminder_logs_id_seq to service_role;
grant select, insert, update on public.reminder_logs to service_role;
