create table if not exists public.self_evaluations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_of date not null,
  rating_rendimento smallint check (rating_rendimento between 1 and 5),
  rating_entregas smallint check (rating_entregas between 1 and 5),
  rating_consistencia smallint check (rating_consistencia between 1 and 5),
  rating_melhoria smallint check (rating_melhoria between 1 and 5),
  rating_fatores smallint check (rating_fatores between 1 and 5),
  comments text,
  created_at timestamptz not null default now(),
  unique (user_id, week_of)
);

alter table public.self_evaluations enable row level security;

create policy "self_evaluations_insert_own" on public.self_evaluations
  for insert
  with check (auth.uid() = user_id);

create policy "self_evaluations_update_own" on public.self_evaluations
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "self_evaluations_select_own" on public.self_evaluations
  for select
  using (auth.uid() = user_id);

create policy "self_evaluations_select_admin" on public.self_evaluations
  for select
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and (p.user_role = 'Admin' or p.assessoria = 'Recursos Humanos')
    )
  );
